global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'router'
    static_configs:
      - targets: ['router:443']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 